### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by WolfgangFahl** [bohnelang/URN-Pruefziffer#1]
see https://github.com/WolfgangFahl/pyCEURmake/issues/88

**Comment by bohnelang** [comment]
Hallo, ich haben den Algorithmus nun noch auf der github-Seite beschrieben. Die Beschreibung des Algorithumus, welche mal auf der Seite der DNB vorhanden war, finde ich gerade nicht. Vermutlich wäres es einfacher gewesen, die Idee des Algorithmus in python manuell zu übertragen, anstatt auf Chat GPT die sprache übersetzen zu lassen. Die if-Abfrage auf ='#' ist überflüssig, da es sich hierbei um einen Bereich handelt, der nie angesprochen wird, da er nicht definiert ist.

**Comment by WolfgangFahl** [comment]
Danke sehr. Ich hätte den Algorithmus nicht so flott in python umstellen können. Dafür ist er IMHO zu komplex. Die Komplexität zu verbergen ist IMHO daher eine gute Idee. Für den CEUR-WS Fall war ich froh, hier fündig geworden zu sein.
